[theme]
base                     = "light"
primaryColor             = "#D97706"
backgroundColor          = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#111827"
font                     = "sans serif"

[server]
headless             = true
enableCORS           = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
